# Image reference used by `make docker-build` / `make docker-push`.
# Override for a custom registry, e.g.:
#   make docker-push IMG=ghcr.io/your-org/profi:v0.1.0
TAG ?= $(shell git describe --tags 2>/dev/null || echo latest)
IMG ?= profi:$(TAG)

BPF_C := src/bpf/profi.bpf.c
BPF_HEADERS := src/bpf/profi_events.h
LIBBPF_INCLUDE ?= $(shell sh -c 'p=$$(find target/debug/build target/release/build -path "*/out/include/bpf/bpf_helpers.h" -print -quit 2>/dev/null); [ -n "$$p" ] && dirname "$$(dirname "$$p")"')
BPF_CLANG_ARGS := -target bpf -Isrc/bpf $(if $(LIBBPF_INCLUDE),-I$(LIBBPF_INCLUDE),) -D__TARGET_ARCH_x86 -D__bpf__
BPF_OBJ := /tmp/profi.bpf.o

.PHONY: help build check fmt fmt-fix c-fmt c-fmt-check c-tidy bpf-compile bpf-verify clippy lint test prek-install prek-run docker-build docker-push clean

help: ## Show this help
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  %-14s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

build: ## Build profi (BPF skeleton auto-generated by build.rs; needs clang in PATH)
	cargo build --package profi --release

check: ## cargo check
	cargo check

fmt: ## Verify formatting
	cargo fmt --all -- --check

fmt-fix: ## Auto-format sources
	cargo fmt --all

c-fmt: ## Format eBPF C sources
	clang-format -i $(BPF_C) $(BPF_HEADERS)

c-fmt-check: ## Verify eBPF C formatting
	clang-format --dry-run --Werror $(BPF_C) $(BPF_HEADERS)

c-tidy: ## Run clang-tidy on eBPF C sources
	@test -n "$(LIBBPF_INCLUDE)" || (echo "libbpf headers not found; run 'cargo check --package profi' first" >&2; exit 1)
	clang-tidy $(BPF_C) -- $(BPF_CLANG_ARGS)

bpf-compile: ## Compile eBPF C source to a temporary BPF object
	@test -n "$(LIBBPF_INCLUDE)" || (echo "libbpf headers not found; run 'cargo check --package profi' first" >&2; exit 1)
	clang -O2 -g $(BPF_CLANG_ARGS) -c $(BPF_C) -o $(BPF_OBJ)

bpf-verify: bpf-compile ## Load temporary BPF object through the kernel verifier (requires privileges)
	bpftool prog loadall $(BPF_OBJ) /sys/fs/bpf/profi-verify
	rm -f /sys/fs/bpf/profi-verify/*
	rmdir /sys/fs/bpf/profi-verify

clippy: ## Run clippy, deny warnings
	cargo clippy --all-targets -- -D warnings

lint: fmt c-fmt-check clippy ## fmt + C format check + clippy

test: ## Run workspace tests
	cargo test

prek-install: ## Install local git hooks via prek
	prek install --install-hooks

prek-run: ## Run all configured prek hooks on all files
	prek run --all-files

docker-build: ## Build container image tagged $(IMG)
	docker build -t $(IMG) .

docker-push: ## Push container image $(IMG)
	docker push $(IMG)

clean: ## Remove Rust build artifacts
	cargo clean
